# Site settings
title: Super Confuser User
header-img: img/home-bg.png
email: chelyho@gmail.com
copyright_name: Chely Ho
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  SuperConfuserUser
learn_profile: unenlightened
email_username: chelyho@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
